### ISSUE TITLE
Great playground, but a naming problem on the display itself

### ISSUE THREAD

**Issue by ggonmar** [kazzkiq/svg-color-filter#1]
Hi,
love the tool and the implementation, great work!
However, there's a problem (I believe) with the code displayed on https://kazzkiq.github.io/svg-color-filter/:

The last "</feColorMatrix>" should not be there: the tag is auto enclosed by />, and even if we wanted to close it, it should be done within the <filter> tags :)

**Comment by kazzkiq** [comment]
Hey @ggonmar, I didn't quite got which part you're talking about. Can you send me a screenshot showing where is the problem? Thanks!

**Comment by ggonmar** [comment]
sure thing! 
![image](https://user-images.githubusercontent.com/11583288/37106455-2d1faaca-2232-11e8-8c28-395386b26979.png)

the &lt;/feColorMatrix&gt; I circled is outside the &lt;filter&gt; tags that I marked.

the &lt;feColorMatrix&gt; that actually contains the matrix has the closing  "/&gt;" as marked, so in any case  the  &lt;/feColorMatrix&gt;  is unnecessary...
In the case we wanted to have it, it should be before the &lt;/filter&gt; closing tag.... 

Or at least I believe so! correct me if I'm wrong though!

**Comment by kazzkiq** [comment]
Wow, you're right! I totally missed that. Will be fixing it tonight.

Thanks!
